import type { LightingPreset, LightingPresetId } from "@/types/portfolio";

export const lightingPresets: Record<LightingPresetId, LightingPreset> = {
  livingWarm: {
    id: "livingWarm",
    color: "#ffd9a4",
    accent: "#ffb84d",
    ambient: 0.38,
    activeIntensity: 3.4,
    inactiveIntensity: 0.32,
    fogColor: "#1a1208",
    fogNear: 12,
    fogFar: 38,
    hemiSky: "#ffc98a",
    hemiGround: "#1c0e05",
    hemiIntensity: 0.45,
  },
  musicStage: {
    id: "musicStage",
    color: "#ffd280",
    accent: "#ffaa20",
    ambient: 0.55,
    activeIntensity: 6.0,
    inactiveIntensity: 0.18,
    fogColor: "#1a1408",
    fogNear: 10,
    fogFar: 34,
    hemiSky: "#ffd080",
    hemiGround: "#2a1a06",
    hemiIntensity: 0.72,
  },
  webDigital: {
    id: "webDigital",
    color: "#5cd8ff",
    accent: "#3b82f6",
    ambient: 0.22,
    activeIntensity: 3.2,
    inactiveIntensity: 0.2,
    fogColor: "#020b1f",
    fogNear: 10,
    fogFar: 34,
    hemiSky: "#7dd3fc",
    hemiGround: "#020617",
    hemiIntensity: 0.4,
  },
  creativeWarm: {
    id: "creativeWarm",
    color: "#ffd166",
    accent: "#fb923c",
    ambient: 0.32,
    activeIntensity: 3.25,
    inactiveIntensity: 0.24,
    fogColor: "#1f0d04",
    fogNear: 11,
    fogFar: 32,
    hemiSky: "#ffb86b",
    hemiGround: "#241004",
    hemiIntensity: 0.42,
  },
  eventsGold: {
    id: "eventsGold",
    color: "#ffb84d",
    accent: "#ff4fd8",
    ambient: 0.26,
    activeIntensity: 3.45,
    inactiveIntensity: 0.2,
    fogColor: "#1c0820",
    fogNear: 9,
    fogFar: 30,
    hemiSky: "#ff66c4",
    hemiGround: "#240a26",
    hemiIntensity: 0.36,
  },
  academicsLibrary: {
    id: "academicsLibrary",
    color: "#b6f0c8",
    accent: "#166534",
    ambient: 0.3,
    activeIntensity: 3.0,
    inactiveIntensity: 0.24,
    fogColor: "#06140c",
    fogNear: 12,
    fogFar: 36,
    hemiSky: "#86efac",
    hemiGround: "#0a1f12",
    hemiIntensity: 0.4,
  },
  professionalNavy: {
    id: "professionalNavy",
    color: "#dbeafe",
    accent: "#38bdf8",
    ambient: 0.28,
    activeIntensity: 3.15,
    inactiveIntensity: 0.22,
    fogColor: "#040a18",
    fogNear: 12,
    fogFar: 36,
    hemiSky: "#bfdbfe",
    hemiGround: "#0a1224",
    hemiIntensity: 0.42,
  },
};
