import type { RoomConfig } from "@/types/portfolio";

/**
 * Room layout — pinwheel around a tall central Living hall (no gaps, no wall overlaps).
 * Living hub: 14×22, center (0,-5)  → x[-7,7]  z[-16,6]  (main entrance on south wall, z=6).
 * Left column  (x[-22,-7], 15 wide):  Academics z[-16,-6] (north) + Music z[-6,6] (south).
 * Right column (x[7,22],   15 wide):  Professional z[-16,-6] (north) + Web z[-6,6] (south).
 * Top band     (z[-26,-16], 10 deep): Creative x[-10,0] + Events x[0,10].
 * Living connects: Creative/Events (north wall), Academics/Music (west wall),
 * Professional/Web (east wall); decorative grand entrance on the south wall.
 */
export const rooms: RoomConfig[] = [
  {
    id: "living",
    label: "Living Room",
    tagline: "The hub • Welcome • Personality",
    position: [0, 0, -5],
    size: [14, 0.2, 22],
    themeColor: "#3a2a1f",
    wallColor: "#2a1d14",
    trimColor: "#8a5a2b",
    accentColor: "#ffb84d",
    lightingPreset: "livingWarm",
    entryPoint: [0, 0.7, 3],
    cameraOffset: [0, 13, 18],
    doors: [
      {
        id: "living-to-music",
        label: "Music & Guitar Room",
        fromRoom: "living",
        toRoom: "music",
        position: [-7, 1.4, -2],
        rotation: [0, Math.PI / 2, 0],
        targetPosition: [-8.5, 0.7, -2],
        accentColor: "#ff3d6e",
      },
      {
        id: "living-to-web",
        label: "Web & Digital Services Room",
        fromRoom: "living",
        toRoom: "web",
        position: [7, 1.4, -2],
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: [9, 0.7, -2],
        accentColor: "#34d5ff",
      },
      {
        id: "living-to-academics",
        label: "Academics & Certifications Room",
        fromRoom: "living",
        toRoom: "academics",
        position: [-7, 1.4, -11],
        rotation: [0, Math.PI / 2, 0],
        targetPosition: [-9, 0.7, -11],
        accentColor: "#86efac",
      },
      {
        id: "living-to-professional",
        label: "Professional Work Experience Room",
        fromRoom: "living",
        toRoom: "professional",
        position: [7, 1.4, -11],
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: [9, 0.7, -11],
        accentColor: "#38bdf8",
      },
      {
        id: "living-to-creative",
        label: "Painting, Crafts & Creative Room",
        fromRoom: "living",
        toRoom: "creative",
        position: [-4, 1.4, -16],
        targetPosition: [-4, 0.7, -18.5],
        accentColor: "#fb923c",
      },
      {
        id: "living-to-events",
        label: "Events, Management & Business Room",
        fromRoom: "living",
        toRoom: "events",
        position: [4, 1.4, -16],
        targetPosition: [4, 0.7, -18.5],
        accentColor: "#facc15",
      },
    ],
    objects: [
      {
        id: "welcome-frame",
        label: "Welcome Frame",
        roomId: "living",
        overlayId: "welcome",
        position: [0, 1.5, -15.85],
        shape: "plane",
        accentColor: "#ffb84d",
      },
      {
        id: "contact-laptop",
        label: "Contact Corner",
        roomId: "living",
        overlayId: "contact",
        position: [5, 0.9, 3.5],
        shape: "box",
        accentColor: "#34d399",
      },
      {
        id: "resume-frame",
        label: "Resume",
        roomId: "living",
        overlayId: "resume",
        position: [-5, 1.5, 3.2],
        shape: "plane",
        accentColor: "#f7c66f",
      },
    ],
  },
  {
    id: "music",
    label: "Music Room",
    tagline: "Performance • Guitar • Identity",
    position: [-14.5, 0, 0],
    size: [15, 0.2, 12],
    themeColor: "#141210",
    wallColor: "#2e2e2e",
    trimColor: "#c49a24",
    accentColor: "#ffd060",
    lightingPreset: "musicStage",
    entryPoint: [-8.5, 0.7, -2],
    cameraOffset: [0, 9.0, 12.0],
    doors: [
      {
        id: "music-to-living",
        label: "Return to Living Room",
        fromRoom: "music",
        toRoom: "living",
        position: [-7, 1.4, -2],
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: [-5.5, 0.7, -2],
        accentColor: "#ffb84d",
      },
    ],
    objects: [],
  },
  {
    id: "web",
    label: "Web Room",
    tagline: "Digital • Systems • Automation",
    position: [14.5, 0, 0],
    size: [15, 0.2, 12],
    themeColor: "#0a132a",
    wallColor: "#070d1f",
    trimColor: "#34d5ff",
    accentColor: "#22d3ee",
    lightingPreset: "webDigital",
    entryPoint: [9, 0.7, -2],
    cameraOffset: [0, 9, 12.5],
    doors: [
      {
        id: "web-to-living",
        label: "Return to Living Room",
        fromRoom: "web",
        toRoom: "living",
        position: [7, 1.4, -2],
        rotation: [0, Math.PI / 2, 0],
        targetPosition: [5.5, 0.7, -2],
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "main-monitor",
        label: "Main Monitor",
        roomId: "web",
        overlayId: "webProjects",
        position: [14.5, 1.2, -5.85],
        shape: "plane",
        accentColor: "#34d5ff",
      },
      {
        id: "whiteboard",
        label: "Tech Stack Whiteboard",
        roomId: "web",
        overlayId: "techStack",
        position: [21.85, 1.5, -2],
        shape: "plane",
        accentColor: "#93c5fd",
      },
      {
        id: "dashboard-screen",
        label: "Product Case Studies",
        roomId: "web",
        overlayId: "productCaseStudies",
        position: [12.9, 1.3, 1.5],
        shape: "plane",
        accentColor: "#22d3ee",
      },
      {
        id: "server-rack",
        label: "Automation Systems",
        roomId: "web",
        overlayId: "automationSystems",
        position: [20.5, 1, 1.7],
        shape: "box",
        accentColor: "#3b82f6",
      },
    ],
  },
  {
    id: "creative",
    label: "Creative Room",
    tagline: "Craft • Art • Expression",
    position: [-5, 0, -21],
    size: [10, 0.2, 10],
    themeColor: "#2c160a",
    wallColor: "#1f0e05",
    trimColor: "#fb923c",
    accentColor: "#ffd166",
    lightingPreset: "creativeWarm",
    entryPoint: [-4, 0.7, -18.5],
    cameraOffset: [0, 8, 10.2],
    doors: [
      {
        id: "creative-to-living",
        label: "Return to Living Room",
        fromRoom: "creative",
        toRoom: "living",
        position: [-4, 1.4, -16],
        rotation: [0, Math.PI, 0],
        targetPosition: [-4, 0.7, -14.5],
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "jewelry-table",
        label: "Jewelry Table",
        roomId: "creative",
        overlayId: "beadsBonita",
        position: [-8, 0.9, -22],
        shape: "box",
        accentColor: "#f97316",
      },
      {
        id: "painting-wall",
        label: "Artwork Gallery",
        roomId: "creative",
        overlayId: "artworkGallery",
        position: [-5, 1.6, -25.2],
        shape: "plane",
        accentColor: "#ffd166",
      },
      {
        id: "sketchbook",
        label: "Sketchbook",
        roomId: "creative",
        overlayId: "creativeDirection",
        position: [-2.4, 0.85, -21.8],
        shape: "box",
        accentColor: "#fb923c",
      },
    ],
  },
  {
    id: "events",
    label: "Events Room",
    tagline: "Production • Campaigns • Brand",
    position: [5, 0, -21],
    size: [10, 0.2, 10],
    themeColor: "#240e22",
    wallColor: "#1a081a",
    trimColor: "#ff4fd8",
    accentColor: "#facc15",
    lightingPreset: "eventsGold",
    entryPoint: [4, 0.7, -18.5],
    cameraOffset: [0, 7.6, 9.6],
    doors: [
      {
        id: "events-to-living",
        label: "Return to Living Room",
        fromRoom: "events",
        toRoom: "living",
        position: [4, 1.4, -16],
        rotation: [0, Math.PI, 0],
        targetPosition: [4, 0.7, -14.5],
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "planning-board",
        label: "Planning Board",
        roomId: "events",
        overlayId: "eventCaseStudies",
        position: [2.2, 1.4, -23.8],
        shape: "plane",
        accentColor: "#facc15",
      },
      {
        id: "campaign-wall",
        label: "Campaign Wall",
        roomId: "events",
        overlayId: "campaignHighlights",
        position: [5, 1.6, -25.2],
        shape: "plane",
        accentColor: "#ff4fd8",
      },
      {
        id: "ticket-counter",
        label: "Ticket Counter",
        roomId: "events",
        overlayId: "eventPortfolio",
        position: [7.8, 0.85, -21.7],
        shape: "box",
        accentColor: "#f59e0b",
      },
      {
        id: "business-desk",
        label: "Business Desk",
        roomId: "events",
        overlayId: "entrepreneurship",
        position: [3, 0.85, -19],
        shape: "box",
        accentColor: "#fde68a",
      },
    ],
  },
  {
    id: "academics",
    label: "Academics Room",
    tagline: "Study • Research • Calm",
    position: [-14.5, 0, -11],
    size: [15, 0.2, 10],
    themeColor: "#0e1f14",
    wallColor: "#08160d",
    trimColor: "#86efac",
    accentColor: "#bbf7d0",
    lightingPreset: "academicsLibrary",
    entryPoint: [-9, 0.7, -11],
    cameraOffset: [0, 9, 12],
    doors: [
      {
        id: "academics-to-living",
        label: "Return to Living Room",
        fromRoom: "academics",
        toRoom: "living",
        position: [-7, 1.4, -11],
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: [-5.5, 0.7, -11],
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "certificate-wall",
        label: "Certificate Wall",
        roomId: "academics",
        overlayId: "certifications",
        position: [-21.85, 1.6, -9],
        shape: "plane",
        accentColor: "#86efac",
      },
      {
        id: "research-frame",
        label: "Research Frame",
        roomId: "academics",
        overlayId: "researchPublication",
        position: [-21.85, 1.6, -12.5],
        shape: "plane",
        accentColor: "#bbf7d0",
      },
      {
        id: "bookshelf",
        label: "Bookshelf",
        roomId: "academics",
        overlayId: "academicBackground",
        position: [-10, 1.1, -15.4],
        shape: "box",
        accentColor: "#166534",
      },
    ],
  },
  {
    id: "professional",
    label: "Professional Room",
    tagline: "Executive • Strategy • Impact",
    position: [14.5, 0, -11],
    size: [15, 0.2, 10],
    themeColor: "#0a1226",
    wallColor: "#070d1c",
    trimColor: "#38bdf8",
    accentColor: "#93c5fd",
    lightingPreset: "professionalNavy",
    entryPoint: [9, 0.7, -11],
    cameraOffset: [0, 9, 12],
    doors: [
      {
        id: "professional-to-living",
        label: "Return to Living Room",
        fromRoom: "professional",
        toRoom: "living",
        position: [7, 1.4, -11],
        rotation: [0, Math.PI / 2, 0],
        targetPosition: [5.5, 0.7, -11],
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "timeline-wall",
        label: "Career Timeline",
        roomId: "professional",
        overlayId: "careerTimeline",
        position: [10, 1.5, -6.1],
        shape: "plane",
        accentColor: "#dbeafe",
      },
      {
        id: "kpi-dashboard",
        label: "KPI Dashboard",
        roomId: "professional",
        overlayId: "professionalImpact",
        position: [14.5, 1.4, -6.1],
        shape: "plane",
        accentColor: "#38bdf8",
      },
      {
        id: "project-board",
        label: "Project Board",
        roomId: "professional",
        overlayId: "professionalCaseStudies",
        position: [19, 1.4, -6.1],
        shape: "plane",
        accentColor: "#93c5fd",
      },
      {
        id: "workflow-diagram",
        label: "Workflow Diagram",
        roomId: "professional",
        overlayId: "workflowSystems",
        position: [14.5, 1, -12],
        shape: "box",
        accentColor: "#60a5fa",
      },
    ],
  },
];

export const roomById = Object.fromEntries(rooms.map((room) => [room.id, room])) as Record<
  RoomConfig["id"],
  RoomConfig
>;

export const allDoors = rooms.flatMap((room) => room.doors);
export const allInteractiveObjects = rooms.flatMap((room) => room.objects);
