import type { RoomConfig } from "@/types/portfolio";
import { scaleDepth, scaleWorldZ, worldPos } from "@/lib/roomLayout";

/**
 * Room layout — pinwheel around a tall central Living hall (no gaps, no wall overlaps).
 * Depths are ×1.3 from the pre-expansion layout (pivot: south entrance z = 6).
 *
 * Living hub: 14×28.6, center (0,-8.3) → x[-7,7] z[-22.6,6].
 * Left column  (x[-22,-7], 15 wide): Academics z[-22.6,-9.6] + Music z[-9.6,6].
 * Right column (x[7,22], 15 wide):    Professional z[-22.6,-9.6] + Web z[-9.6,6].
 * Top band     (z[-35.6,-22.6], 13 deep): Creative x[-10,0] + Events x[0,10].
 */
export const rooms: RoomConfig[] = [
  {
    id: "living",
    label: "Living Room",
    tagline: "The hub • Welcome • Personality",
    position: [0, 0, scaleWorldZ(-5)],
    size: [14, 0.2, scaleDepth(22)],
    themeColor: "#3a2a1f",
    wallColor: "#2a1d14",
    trimColor: "#8a5a2b",
    accentColor: "#ffb84d",
    lightingPreset: "livingWarm",
    entryPoint: worldPos(0, 0.7, 3),
    cameraOffset: [0, 13, 18],
    doors: [
      {
        id: "living-to-music",
        label: "Music & Guitar Room",
        fromRoom: "living",
        toRoom: "music",
        position: worldPos(-7, 1.4, -2),
        rotation: [0, Math.PI / 2, 0],
        targetPosition: worldPos(-8.5, 0.7, -2),
        accentColor: "#ff3d6e",
      },
      {
        id: "living-to-web",
        label: "Web & Digital Services Room",
        fromRoom: "living",
        toRoom: "web",
        position: worldPos(7, 1.4, -2),
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: worldPos(9, 0.7, -2),
        accentColor: "#34d5ff",
      },
      {
        id: "living-to-academics",
        label: "Academics & Certifications Room",
        fromRoom: "living",
        toRoom: "academics",
        position: worldPos(-7, 1.4, -11),
        rotation: [0, Math.PI / 2, 0],
        targetPosition: worldPos(-9, 0.7, -11),
        accentColor: "#86efac",
      },
      {
        id: "living-to-professional",
        label: "Professional Work Experience Room",
        fromRoom: "living",
        toRoom: "professional",
        position: worldPos(7, 1.4, -11),
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: worldPos(9, 0.7, -11),
        accentColor: "#38bdf8",
      },
      {
        id: "living-to-creative",
        label: "Painting, Crafts & Creative Room",
        fromRoom: "living",
        toRoom: "creative",
        position: worldPos(-4, 1.4, -16),
        targetPosition: worldPos(-4, 0.7, -18.5),
        accentColor: "#fb923c",
      },
      {
        id: "living-to-events",
        label: "Events, Management & Business Room",
        fromRoom: "living",
        toRoom: "events",
        position: worldPos(4, 1.4, -16),
        targetPosition: worldPos(4, 0.7, -18.5),
        accentColor: "#facc15",
      },
    ],
    objects: [
      {
        id: "welcome-frame",
        label: "Welcome Frame",
        roomId: "living",
        overlayId: "welcome",
        position: worldPos(0, 1.5, -15.85),
        shape: "plane",
        accentColor: "#ffb84d",
      },
      {
        id: "contact-laptop",
        label: "Contact Corner",
        roomId: "living",
        overlayId: "contact",
        position: worldPos(5, 0.9, 3.5),
        shape: "box",
        accentColor: "#34d399",
      },
      {
        id: "resume-frame",
        label: "Resume",
        roomId: "living",
        overlayId: "resume",
        position: worldPos(-5, 1.5, 3.2),
        shape: "plane",
        accentColor: "#f7c66f",
      },
    ],
  },
  {
    id: "music",
    label: "Music Room",
    tagline: "Performance • Guitar • Identity",
    position: [-14.5, 0, scaleWorldZ(0)],
    size: [15, 0.2, scaleDepth(12)],
    themeColor: "#141210",
    wallColor: "#2e2e2e",
    trimColor: "#c49a24",
    accentColor: "#ffd060",
    lightingPreset: "musicStage",
    entryPoint: worldPos(-8.5, 0.7, -2),
    cameraOffset: [0, 9.0, 12.0],
    doors: [
      {
        id: "music-to-living",
        label: "Return to Living Room",
        fromRoom: "music",
        toRoom: "living",
        position: worldPos(-7, 1.4, -2),
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: worldPos(-5.5, 0.7, -2),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "tv-screen",
        label: "TV Screen",
        roomId: "music",
        overlayId: "musicTvMenu",
        position: worldPos(-14.5, 0.7, -4.85),
        proximityOnly: true,
        accentColor: "#ffd060",
      },
    ],
  },
  {
    id: "web",
    label: "Web Room",
    tagline: "Digital • Systems • Automation",
    position: [14.5, 0, scaleWorldZ(0)],
    size: [15, 0.2, scaleDepth(12)],
    themeColor: "#0a132a",
    wallColor: "#070d1f",
    trimColor: "#34d5ff",
    accentColor: "#22d3ee",
    lightingPreset: "webDigital",
    entryPoint: worldPos(9, 0.7, -2),
    cameraOffset: [0, 9, 12.5],
    doors: [
      {
        id: "web-to-living",
        label: "Return to Living Room",
        fromRoom: "web",
        toRoom: "living",
        position: worldPos(7, 1.4, -2),
        rotation: [0, Math.PI / 2, 0],
        targetPosition: worldPos(5.5, 0.7, -2),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "main-monitor",
        label: "Main Monitor",
        roomId: "web",
        overlayId: "webProjects",
        position: worldPos(14.5, 1.2, -5.85),
        shape: "plane",
        accentColor: "#34d5ff",
      },
      {
        id: "whiteboard",
        label: "Tech Stack Whiteboard",
        roomId: "web",
        overlayId: "techStack",
        position: worldPos(21.85, 1.5, -2),
        shape: "plane",
        accentColor: "#93c5fd",
      },
      {
        id: "dashboard-screen",
        label: "Product Case Studies",
        roomId: "web",
        overlayId: "productCaseStudies",
        position: worldPos(12.9, 1.3, 1.5),
        shape: "plane",
        accentColor: "#22d3ee",
      },
      {
        id: "server-rack",
        label: "Automation Systems",
        roomId: "web",
        overlayId: "automationSystems",
        position: worldPos(20.5, 1, 1.7),
        shape: "box",
        accentColor: "#3b82f6",
      },
    ],
  },
  {
    id: "creative",
    label: "Creative Room",
    tagline: "Craft • Art • Expression",
    position: [-5, 0, scaleWorldZ(-21)],
    size: [10, 0.2, scaleDepth(10)],
    themeColor: "#2c160a",
    wallColor: "#1f0e05",
    trimColor: "#fb923c",
    accentColor: "#ffd166",
    lightingPreset: "creativeWarm",
    entryPoint: worldPos(-4, 0.7, -18.5),
    cameraOffset: [0, 8, 10.2],
    doors: [
      {
        id: "creative-to-living",
        label: "Return to Living Room",
        fromRoom: "creative",
        toRoom: "living",
        position: worldPos(-4, 1.4, -16),
        rotation: [0, Math.PI, 0],
        targetPosition: worldPos(-4, 0.7, -14.5),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "jewelry-table",
        label: "Jewelry Table",
        roomId: "creative",
        overlayId: "beadsBonita",
        position: worldPos(-8, 0.9, -22),
        shape: "box",
        accentColor: "#f97316",
      },
      {
        id: "painting-wall",
        label: "Artwork Gallery",
        roomId: "creative",
        overlayId: "artworkGallery",
        position: worldPos(-5, 1.6, -25.2),
        shape: "plane",
        accentColor: "#ffd166",
      },
      {
        id: "sketchbook",
        label: "Sketchbook",
        roomId: "creative",
        overlayId: "creativeDirection",
        position: worldPos(-2.4, 0.85, -21.8),
        shape: "box",
        accentColor: "#fb923c",
      },
    ],
  },
  {
    id: "events",
    label: "Events Room",
    tagline: "Production • Campaigns • Brand",
    position: [5, 0, scaleWorldZ(-21)],
    size: [10, 0.2, scaleDepth(10)],
    themeColor: "#240e22",
    wallColor: "#1a081a",
    trimColor: "#ff4fd8",
    accentColor: "#facc15",
    lightingPreset: "eventsGold",
    entryPoint: worldPos(4, 0.7, -18.5),
    cameraOffset: [0, 7.6, 9.6],
    doors: [
      {
        id: "events-to-living",
        label: "Return to Living Room",
        fromRoom: "events",
        toRoom: "living",
        position: worldPos(4, 1.4, -16),
        rotation: [0, Math.PI, 0],
        targetPosition: worldPos(4, 0.7, -14.5),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "planning-board",
        label: "Planning Board",
        roomId: "events",
        overlayId: "eventCaseStudies",
        position: worldPos(2.2, 1.4, -23.8),
        shape: "plane",
        accentColor: "#facc15",
      },
      {
        id: "campaign-wall",
        label: "Campaign Wall",
        roomId: "events",
        overlayId: "campaignHighlights",
        position: worldPos(5, 1.6, -25.2),
        shape: "plane",
        accentColor: "#ff4fd8",
      },
      {
        id: "ticket-counter",
        label: "Ticket Counter",
        roomId: "events",
        overlayId: "eventPortfolio",
        position: worldPos(7.8, 0.85, -21.7),
        shape: "box",
        accentColor: "#f59e0b",
      },
      {
        id: "business-desk",
        label: "Business Desk",
        roomId: "events",
        overlayId: "entrepreneurship",
        position: worldPos(3, 0.85, -19),
        shape: "box",
        accentColor: "#fde68a",
      },
    ],
  },
  {
    id: "academics",
    label: "Academics Room",
    tagline: "Study • Research • Calm",
    position: [-14.5, 0, scaleWorldZ(-11)],
    size: [15, 0.2, scaleDepth(10)],
    themeColor: "#0e1f14",
    wallColor: "#08160d",
    trimColor: "#86efac",
    accentColor: "#bbf7d0",
    lightingPreset: "academicsLibrary",
    entryPoint: worldPos(-9, 0.7, -11),
    cameraOffset: [0, 9, 12],
    doors: [
      {
        id: "academics-to-living",
        label: "Return to Living Room",
        fromRoom: "academics",
        toRoom: "living",
        position: worldPos(-7, 1.4, -11),
        rotation: [0, -Math.PI / 2, 0],
        targetPosition: worldPos(-5.5, 0.7, -11),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "certificate-wall",
        label: "Certificate Wall",
        roomId: "academics",
        overlayId: "certifications",
        position: worldPos(-21.85, 1.6, -9),
        shape: "plane",
        accentColor: "#86efac",
      },
      {
        id: "research-frame",
        label: "Research Frame",
        roomId: "academics",
        overlayId: "researchPublication",
        position: worldPos(-21.85, 1.6, -12.5),
        shape: "plane",
        accentColor: "#bbf7d0",
      },
      {
        id: "bookshelf",
        label: "Bookshelf",
        roomId: "academics",
        overlayId: "academicBackground",
        position: worldPos(-10, 1.1, -15.4),
        shape: "box",
        accentColor: "#166534",
      },
    ],
  },
  {
    id: "professional",
    label: "Professional Room",
    tagline: "Executive • Strategy • Impact",
    position: [14.5, 0, scaleWorldZ(-11)],
    size: [15, 0.2, scaleDepth(10)],
    themeColor: "#0a1226",
    wallColor: "#070d1c",
    trimColor: "#38bdf8",
    accentColor: "#93c5fd",
    lightingPreset: "professionalNavy",
    entryPoint: worldPos(9, 0.7, -11),
    cameraOffset: [0, 9, 12],
    doors: [
      {
        id: "professional-to-living",
        label: "Return to Living Room",
        fromRoom: "professional",
        toRoom: "living",
        position: worldPos(7, 1.4, -11),
        rotation: [0, Math.PI / 2, 0],
        targetPosition: worldPos(5.5, 0.7, -11),
        accentColor: "#ffb84d",
      },
    ],
    objects: [
      {
        id: "timeline-wall",
        label: "Career Timeline",
        roomId: "professional",
        overlayId: "careerTimeline",
        position: worldPos(10, 1.5, -6.1),
        shape: "plane",
        accentColor: "#dbeafe",
      },
      {
        id: "kpi-dashboard",
        label: "KPI Dashboard",
        roomId: "professional",
        overlayId: "professionalImpact",
        position: worldPos(14.5, 1.4, -6.1),
        shape: "plane",
        accentColor: "#38bdf8",
      },
      {
        id: "project-board",
        label: "Project Board",
        roomId: "professional",
        overlayId: "professionalCaseStudies",
        position: worldPos(19, 1.4, -6.1),
        shape: "plane",
        accentColor: "#93c5fd",
      },
      {
        id: "workflow-diagram",
        label: "Workflow Diagram",
        roomId: "professional",
        overlayId: "workflowSystems",
        position: worldPos(14.5, 1, -12),
        shape: "box",
        accentColor: "#60a5fa",
      },
    ],
  },
];

export const roomById = Object.fromEntries(rooms.map((room) => [room.id, room])) as Record<
  RoomConfig["id"],
  RoomConfig
>;

export const allDoors = rooms.flatMap((room) => room.doors);
export const allInteractiveObjects = rooms.flatMap((room) => room.objects);
